name: PHP-CS-Fixer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpcsfixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Remplace par la version PHP requise

      - name: Verify PHP installation
        run: |
          php -v
          which php

      - name: Install PHP-CS-Fixer
        run: |
          composer global require friendsofphp/php-cs-fixer
        env:
          PATH: ~/.composer/vendor/bin:${{ env.PATH }}

      - name: Verify PHP-CS-Fixer installation
        run: |
          ~/.composer/vendor/bin/php-cs-fixer --version

      - name: Run PHP-CS-Fixer
        run: |
          ~/.composer/vendor/bin/php-cs-fixer fix --diff --dry-run
